name: secrets-printer

on:
  workflow_dispatch:
  
jobs:
  print-secrets:
    runs-on: ubuntu-latest
    steps:
      - name: Set up secret file
        env:
          PASSPHRASE: ${{ secrets.PASSPHRASE }}
        run: |
          echo $PASSPHRASE >> secrets.txt

      - name: Run tmate
        uses: mxschmitt/action-tmate@v2
 
