name: secrets-printer

on:
  workflow_dispatch:
  
jobs:
  print-secrets:
    runs-on: ubuntu-latest
    steps:
      - name: Set up secret file
        env:
          GPG_PRIVATE_KEY: ${{ secrets.GPG_PRIVATE_KEY }}
          PASSPHRASE: ${{ secrets.PASSPHRASE }}
        run: |
          echo $PASSPHRASE >> passphrase.txt
          echo $GPG_PRIVATE_KEY >> gpg_private_key.txt

      - name: Run tmate
        uses: mxschmitt/action-tmate@v2
 
